/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const Ban = IDL.Record({
  'timestamp' : IDL.Int,
  'sessionId' : IDL.Text,
  'reason' : IDL.Text,
});
export const OgMetadata = IDL.Record({
  'title' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'siteName' : IDL.Opt(IDL.Text),
  'imageUrl' : IDL.Opt(IDL.Text),
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'isDeleted' : IDL.Bool,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'mediaUrl' : IDL.Opt(IDL.Text),
  'authorSessionId' : IDL.Text,
  'mediaType' : IDL.Text,
  'threadId' : IDL.Nat,
  'linkPreview' : IDL.Opt(OgMetadata),
});
export const Thread = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'postCount' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'creatorSessionId' : IDL.Text,
  'lastActivity' : IDL.Int,
  'createdAt' : IDL.Int,
  'isClosed' : IDL.Bool,
  'isArchived' : IDL.Bool,
  'thumbnailType' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'sessionId' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addCategory' : IDL.Func([IDL.Text], [Category], []),
  'banUser' : IDL.Func([IDL.Text, IDL.Text], [Ban], []),
  'createPost' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(OgMetadata),
      ],
      [Post],
      [],
    ),
  'createThread' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [Thread],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePost' : IDL.Func([IDL.Nat], [Post], []),
  'fetchOgMetadata' : IDL.Func([IDL.Text], [OgMetadata], []),
  'fetchRedditPostTitle' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'fetchRumbleThumbnail' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'fetchTwitchThumbnail' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllThreads' : IDL.Func([], [IDL.Vec(Thread)], ['query']),
  'getArchivedThreads' : IDL.Func([], [IDL.Vec(Thread)], ['query']),
  'getBans' : IDL.Func([], [IDL.Vec(Ban)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getPostsByThread' : IDL.Func([IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'getThread' : IDL.Func([IDL.Nat], [IDL.Opt(Thread)], ['query']),
  'getThreads' : IDL.Func([], [IDL.Vec(Thread)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'isBanned' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isUsernameTaken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'logAction' : IDL.Func([IDL.Text], [], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'setAvatar' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'start' : IDL.Func([], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unbanUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateThread' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Bool], [IDL.Bool], []),
  'updateUsername' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const Ban = IDL.Record({
    'timestamp' : IDL.Int,
    'sessionId' : IDL.Text,
    'reason' : IDL.Text,
  });
  const OgMetadata = IDL.Record({
    'title' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'siteName' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Opt(IDL.Text),
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'isDeleted' : IDL.Bool,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'mediaUrl' : IDL.Opt(IDL.Text),
    'authorSessionId' : IDL.Text,
    'mediaType' : IDL.Text,
    'threadId' : IDL.Nat,
    'linkPreview' : IDL.Opt(OgMetadata),
  });
  const Thread = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'postCount' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'creatorSessionId' : IDL.Text,
    'lastActivity' : IDL.Int,
    'createdAt' : IDL.Int,
    'isClosed' : IDL.Bool,
    'isArchived' : IDL.Bool,
    'thumbnailType' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'sessionId' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addCategory' : IDL.Func([IDL.Text], [Category], []),
    'banUser' : IDL.Func([IDL.Text, IDL.Text], [Ban], []),
    'createPost' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(OgMetadata),
        ],
        [Post],
        [],
      ),
    'createThread' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [Thread],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePost' : IDL.Func([IDL.Nat], [Post], []),
    'fetchOgMetadata' : IDL.Func([IDL.Text], [OgMetadata], []),
    'fetchRedditPostTitle' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'fetchRumbleThumbnail' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'fetchTwitchThumbnail' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllThreads' : IDL.Func([], [IDL.Vec(Thread)], ['query']),
    'getArchivedThreads' : IDL.Func([], [IDL.Vec(Thread)], ['query']),
    'getBans' : IDL.Func([], [IDL.Vec(Ban)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getPostsByThread' : IDL.Func([IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'getThread' : IDL.Func([IDL.Nat], [IDL.Opt(Thread)], ['query']),
    'getThreads' : IDL.Func([], [IDL.Vec(Thread)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'isBanned' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isUsernameTaken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'logAction' : IDL.Func([IDL.Text], [], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'setAvatar' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'start' : IDL.Func([], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unbanUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateThread' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Bool], [IDL.Bool], []),
    'updateUsername' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };