/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Ban {
  'timestamp' : bigint,
  'sessionId' : string,
  'reason' : string,
}
export interface Bookmark {
  'id' : bigint,
  'createdAt' : bigint,
  'targetType' : string,
  'sessionId' : string,
  'targetId' : bigint,
}
export interface Category { 'id' : bigint, 'name' : string }
export interface OgMetadata {
  'title' : [] | [string],
  'description' : [] | [string],
  'siteName' : [] | [string],
  'imageUrl' : [] | [string],
}
export interface Post {
  'id' : bigint,
  'isDeleted' : boolean,
  'content' : string,
  'createdAt' : bigint,
  'mediaUrl' : [] | [string],
  'authorSessionId' : string,
  'mediaType' : string,
  'threadId' : bigint,
  'linkPreview' : [] | [OgMetadata],
}
export interface Thread {
  'id' : bigint,
  'categoryId' : bigint,
  'postCount' : bigint,
  'title' : string,
  'reportCount' : bigint,
  'thumbnailUrl' : [] | [string],
  'creatorSessionId' : string,
  'lastActivity' : bigint,
  'createdAt' : bigint,
  'isClosed' : boolean,
  'isArchived' : boolean,
  'viewCount' : bigint,
  'thumbnailType' : string,
}
export interface ThreadReport {
  'id' : bigint,
  'reporterSessionId' : string,
  'createdAt' : bigint,
  'threadId' : bigint,
  'reason' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'daysActive' : bigint,
  'username' : string,
  'lastActiveDate' : bigint,
  'level' : string,
  'avatarUrl' : [] | [string],
  'sessionId' : string,
  'points' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addBookmark' : ActorMethod<[string, string, bigint], Bookmark>,
  'addCategory' : ActorMethod<[string], Category>,
  'awardPoints' : ActorMethod<[string, bigint], [] | [UserProfile]>,
  'banUser' : ActorMethod<[string, string], Ban>,
  'checkDailyActivity' : ActorMethod<[string], UserProfile>,
  'createPost' : ActorMethod<
    [bigint, string, string, [] | [string], string, [] | [OgMetadata]],
    Post
  >,
  'createThread' : ActorMethod<
    [string, bigint, string, [] | [string], string],
    Thread
  >,
  'deleteCategory' : ActorMethod<[bigint], boolean>,
  'deletePost' : ActorMethod<[bigint], Post>,
  'fetchOgMetadata' : ActorMethod<[string], OgMetadata>,
  'fetchRedditPostTitle' : ActorMethod<[string], [] | [string]>,
  'fetchRumbleOgMetadata' : ActorMethod<[string], OgMetadata>,
  'fetchRumbleThumbnail' : ActorMethod<[string], [] | [string]>,
  'fetchTwitchThumbnail' : ActorMethod<[string], [] | [string]>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getAllProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getAllThreads' : ActorMethod<[], Array<Thread>>,
  'getArchivedThreads' : ActorMethod<[], Array<Thread>>,
  'getBans' : ActorMethod<[], Array<Ban>>,
  'getBookmarks' : ActorMethod<[string], Array<Bookmark>>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getPostsByThread' : ActorMethod<[bigint], Array<Post>>,
  'getProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'getSortedThreads' : ActorMethod<[], Array<Thread>>,
  'getThread' : ActorMethod<[bigint], [] | [Thread]>,
  'getThreadReports' : ActorMethod<[], Array<ThreadReport>>,
  'getThreads' : ActorMethod<[], Array<Thread>>,
  'initialize' : ActorMethod<[], undefined>,
  'isBanned' : ActorMethod<[string], boolean>,
  'isUsernameTaken' : ActorMethod<[string], boolean>,
  'logAction' : ActorMethod<[string], undefined>,
  'recordView' : ActorMethod<[bigint, string], boolean>,
  'registerUser' : ActorMethod<
    [string, string],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'removeBookmark' : ActorMethod<[string, bigint], boolean>,
  'reportThread' : ActorMethod<[bigint, string, string], ThreadReport>,
  'setAvatar' : ActorMethod<
    [string, [] | [string]],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'start' : ActorMethod<[], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unbanUser' : ActorMethod<[string], boolean>,
  'updateThread' : ActorMethod<[bigint, boolean, boolean], boolean>,
  'updateUsername' : ActorMethod<
    [string, string],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];